import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { format } from 'npm:date-fns@3.6.0';

// Daily Stand-up — runs every morning and emails admins/supervisors a plain-
// English digest of what needs attention today: rigs overdue for maintenance,
// critical safety actions, and how many crew are on site across all projects.
// Replaces the 30-minute morning phone round-robin.
export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const e = base44.asServiceRole.entities;
    const today = format(new Date(), 'yyyy-MM-dd');
    const weekStart = (() => { const d = new Date(today + 'T00:00:00'); const day = d.getDay(); const diff = day === 0 ? -6 : 1 - day; d.setDate(d.getDate() + diff); return d.toISOString().slice(0, 10); })();

    // Gather today's data
    const [assets, safetyReports, rotas, staff, vehicles] = await Promise.all([
      e.SiteAsset.list('-created_date', 500),
      e.SafetyReport.filter({ status: 'open' }),
      e.RotaAssignment.filter({ assigned_date: today }),
      e.Staff.filter({ is_active: true }),
      e.Vehicle.list(),
    ]);

    // 1. Rigs overdue or due soon for maintenance
    const rigs = assets.filter(a => (a.is_rig === true || a.asset_type === 'rig'));
    const rigAlerts = rigs.filter(r => r.maintenance_status === 'overdue' || r.maintenance_status === 'due_soon' || r.compliance_status === 'expired');

    // 2. Critical safety actions (from open audits)
    const criticalActions = [];
    safetyReports.forEach(r => {
      (r.action_items || []).forEach(a => {
        if (a.priority === 'critical' || a.priority === 'high') {
          criticalActions.push({ audit: r.audit_title || r.site_name, description: a.description, priority: a.priority, due: a.due_date });
        }
      });
    });

    // 3. Crew on site today
    const crewToday = [...new Set(rotas.map(r => r.staff_id))].length;
    const activeJobs = [...new Set(rotas.map(r => r.job_id))].length;

    // 4. Vehicles with service/MOT due soon
    const vehicleAlerts = vehicles.filter(v =>
      (v.mot_expiry && v.mot_expiry <= today) ||
      (v.service_due_date && v.service_due_date <= today)
    );

    // Build the digest
    const lines = [];
    lines.push('=== DAILY STAND-UP DIGEST ===');
    lines.push(`Date: ${format(new Date(), 'EEEE dd MMMM yyyy')}`);
    lines.push('');
    lines.push(`👥 CREW ON SITE TODAY: ${crewToday} staff across ${activeJobs} active job(s)`);
    lines.push('');
    lines.push(`🚜 RIG MAINTENANCE ALERTS: ${rigAlerts.length}`);
    rigAlerts.slice(0, 10).forEach(r => {
      lines.push(`   • ${r.name} — ${r.maintenance_status || r.compliance_status}${r.next_service_date ? ` (next: ${r.next_service_date})` : ''}`);
    });
    if (rigAlerts.length === 0) lines.push('   All rigs healthy ✓');
    lines.push('');
    lines.push(`⚠️  CRITICAL/HIGH SAFETY ACTIONS: ${criticalActions.length}`);
    criticalActions.slice(0, 10).forEach(a => {
      lines.push(`   • [${a.priority.toUpperCase()}] ${a.description}${a.due ? ` (due ${a.due})` : ''}`);
    });
    if (criticalActions.length === 0) lines.push('   No critical safety actions ✓');
    lines.push('');
    lines.push(`🚐 VEHICLE ALERTS: ${vehicleAlerts.length}`);
    vehicleAlerts.slice(0, 8).forEach(v => {
      lines.push(`   • ${v.registration_number || v.name} — MOT ${v.mot_expiry || 'N/A'}, service ${v.service_due_date || 'N/A'}`);
    });
    if (vehicleAlerts.length === 0) lines.push('   All vehicles compliant ✓');
    lines.push('');
    lines.push('Generated by Ground Control Job Planner');

    const digest = lines.join('\n');

    // Email all admins (registered users only)
    const users = await base44.entities.User.list();
    const admins = users.filter(u => u.role === 'admin');
    let emailed = 0;
    for (const admin of admins) {
      try {
        await base44.integrations.Core.SendEmail({
          to: admin.email,
          subject: `☀️ Daily Stand-up — ${format(new Date(), 'dd MMM yyyy')}`,
          body: digest,
        });
        emailed++;
      } catch (err) { /* skip */ }
    }

    return Response.json({
      success: true,
      date: today,
      crew_today: crewToday,
      active_jobs: activeJobs,
      rig_alerts: rigAlerts.length,
      critical_actions: criticalActions.length,
      vehicle_alerts: vehicleAlerts.length,
      admins_emailed: emailed,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}