import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { format } from 'npm:date-fns@3.6.0';
import { escapeHtml, linkBlock, styledHtml, getAppBaseUrl } from '../../shared/emailStyling.ts';

// Daily Stand-up — runs every morning and emails admins/supervisors a plain-
// English digest of what needs attention today: rigs overdue for maintenance,
// critical safety actions, and how many crew are on site across all projects.
// Replaces the 30-minute morning phone round-robin.
export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const e = base44.asServiceRole.entities;
    const today = format(new Date(), 'yyyy-MM-dd');
    const weekStart = (() => { const d = new Date(today + 'T00:00:00'); const day = d.getDay(); const diff = day === 0 ? -6 : 1 - day; d.setDate(d.getDate() + diff); return d.toISOString().slice(0, 10); })();

    // Gather today's data
    const [assets, safetyReports, rotas, staff, vehicles] = await Promise.all([
      e.SiteAsset.list('-created_date', 500),
      e.SafetyReport.filter({ status: 'open' }),
      e.RotaAssignment.filter({ assigned_date: today }),
      e.Staff.filter({ is_active: true }),
      e.Vehicle.list(),
    ]);

    // 1. Rigs overdue or due soon for maintenance
    const rigs = assets.filter(a => (a.is_rig === true || a.asset_type === 'rig'));
    const rigAlerts = rigs.filter(r => r.maintenance_status === 'overdue' || r.maintenance_status === 'due_soon' || r.compliance_status === 'expired');

    // 2. Critical safety actions (from open audits)
    const criticalActions = [];
    safetyReports.forEach(r => {
      (r.action_items || []).forEach(a => {
        if (a.priority === 'critical' || a.priority === 'high') {
          criticalActions.push({ audit: r.audit_title || r.site_name, description: a.description, priority: a.priority, due: a.due_date });
        }
      });
    });

    // 3. Crew on site today
    const crewToday = [...new Set(rotas.map(r => r.staff_id))].length;
    const activeJobs = [...new Set(rotas.map(r => r.job_id))].length;

    // 4. Vehicles with service/MOT due soon
    const vehicleAlerts = vehicles.filter(v =>
      (v.mot_expiry && v.mot_expiry <= today) ||
      (v.service_due_date && v.service_due_date <= today)
    );

    // Build individual sections for token replacement
    const dateStr = format(new Date(), 'EEEE dd MMMM yyyy');
    const rigAlertLines = rigAlerts.slice(0, 10).map(r =>
      `   • ${r.name} — ${r.maintenance_status || r.compliance_status}${r.next_service_date ? ` (next: ${r.next_service_date})` : ''}`
    ).join('\n') || '   All rigs healthy ✓';
    const safetyActionLines = criticalActions.slice(0, 10).map(a =>
      `   • [${a.priority.toUpperCase()}] ${a.description}${a.due ? ` (due ${a.due})` : ''}`
    ).join('\n') || '   No critical safety actions ✓';
    const vehicleAlertLines = vehicleAlerts.slice(0, 8).map(v =>
      `   • ${v.registration_number || v.name} — MOT ${v.mot_expiry || 'N/A'}, service ${v.service_due_date || 'N/A'}`
    ).join('\n') || '   All vehicles compliant ✓';

    // Load email template from settings
    const cfgList = await base44.asServiceRole.entities.EmailAlertSetting.filter({ alert_key: 'daily_standup' });
    const cfg = cfgList[0] || { accent_color: '#0e7a4f', banner_title: 'GC Job Planner', show_banner: true, footer_text: 'GC Job Planner' };
    if (cfg.enabled === false) return Response.json({ skipped: true, reason: 'Email alert disabled' });

    const DEFAULT_STANDUP_TEMPLATE = `=== DAILY STAND-UP DIGEST ===\nDate: {date}\n\nCREW ON SITE TODAY: {crew_on_site} staff across {active_jobs} active job(s)\n\nRIG MAINTENANCE ALERTS: {rig_alert_count}\n{rig_alerts}\n\nCRITICAL/HIGH SAFETY ACTIONS: {safety_action_count}\n{safety_actions}\n\nVEHICLE ALERTS: {vehicle_alert_count}\n{vehicle_alerts}\n\nGenerated by GC Job Planner`;
    const effectiveTemplate = cfg.template || DEFAULT_STANDUP_TEMPLATE;
    const text = effectiveTemplate
      .replace(/\{date\}/g, dateStr)
      .replace(/\{crew_on_site\}/g, String(crewToday))
      .replace(/\{active_jobs\}/g, String(activeJobs))
      .replace(/\{rig_alert_count\}/g, String(rigAlerts.length))
      .replace(/\{rig_alerts\}/g, rigAlertLines)
      .replace(/\{safety_action_count\}/g, String(criticalActions.length))
      .replace(/\{safety_actions\}/g, safetyActionLines)
      .replace(/\{vehicle_alert_count\}/g, String(vehicleAlerts.length))
      .replace(/\{vehicle_alerts\}/g, vehicleAlertLines);
    const subject = cfg.subject
      ? cfg.subject.replace(/\{date\}/g, format(new Date(), 'dd MMM yyyy'))
      : `☀️ Daily Stand-up — ${format(new Date(), 'dd MMM yyyy')}`;

    const baseUrl = await getAppBaseUrl(base44);
    const bodyHtml = escapeHtml(text).replace(/\n/g, '<br>') + linkBlock(baseUrl, '/admin', 'Open planner');

    // Determine recipients
    let recipients = [];
    if (cfg.recipient_emails) {
      recipients = cfg.recipient_emails.split(',').map(s => s.trim()).filter(Boolean);
    }
    if (recipients.length === 0) {
      const users = await base44.asServiceRole.entities.User.list();
      recipients = users.filter(u => u.role === 'admin').map(u => u.email);
    }
    let emailed = 0;
    for (const to of recipients) {
      try {
        await base44.asServiceRole.integrations.Core.SendEmail({
          to,
          subject,
          body: styledHtml(bodyHtml, cfg),
        });
        emailed++;
      } catch (err) { /* skip */ }
    }

    return Response.json({
      success: true,
      date: today,
      crew_today: crewToday,
      active_jobs: activeJobs,
      rig_alerts: rigAlerts.length,
      critical_actions: criticalActions.length,
      vehicle_alerts: vehicleAlerts.length,
      admins_emailed: emailed,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}