import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    // Find idle assets in the yard/depot
    const assets = await base44.asServiceRole.entities.SiteAsset.filter({ is_active: true });
    const assignments = await base44.asServiceRole.entities.JobAssetAssignment.filter({ status: 'assigned' });
    const assignedAssetIds = new Set(assignments.map(a => a.asset_id));

    const idleAssets = assets.filter(a =>
      !assignedAssetIds.has(a.id) &&
      a.storage_location &&
      /depot|yard|dartford/i.test(a.storage_location)
    );

    // Find upcoming deliveries within 3 days that need these assets
    const now = new Date();
    const deliveries = await base44.asServiceRole.entities.DeliveryLog.filter({ status: 'pending' });
    const upcoming = deliveries.filter(d => {
      const dDate = new Date(d.scheduled_date || d.created_date);
      const diffDays = (dDate - now) / (1000 * 60 * 60 * 24);
      return diffDays >= 0 && diffDays <= 3;
    });

    // Match idle assets to deliveries
    const legsToCreate = [];
    for (const delivery of upcoming) {
      const asset = idleAssets.find(a => a.id === delivery.asset_id || a.name === delivery.asset_name);
      if (asset) {
        legsToCreate.push({
          job_id: delivery.job_id || null,
          job_name: delivery.job_name || null,
          asset_id: asset.id,
          asset_name: asset.name,
          leg_type: 'collect',
          leg_sequence: 1,
          from_location: asset.storage_location || 'Depot',
          to_location: delivery.to_location || delivery.job_name || 'Site',
          from_location_type: 'depot',
          to_location_type: 'site',
          scheduled_date: delivery.scheduled_date || new Date().toISOString().slice(0, 10),
          status: 'pending',
          notes: 'Auto-generated by Zero-Idle engine — asset ' + asset.name + ' was idle at ' + (asset.storage_location || 'depot'),
        });
      }
    }

    if (legsToCreate.length === 0) {
      return Response.json({ created: 0, message: 'No idle assets matched to upcoming deliveries' });
    }

    const created = await base44.asServiceRole.entities.DeliveryLeg.bulkCreate(legsToCreate);
    return Response.json({ created: created.length, legs: created });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}